### ISSUE TITLE
Traceback error after install on Elementary OS (ubuntu)

### ISSUE THREAD

**Issue by skippa** [calebmadrigal/trackerjacker#10]
Getting this error after installing

When I run `trackerjacker -h` I get this

`Traceback (most recent call last):
  File "/usr/local/bin/trackerjacker", line 9, in <module>
    load_entry_point('trackerjacker==1.8.7', 'console_scripts', 'trackerjacker')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/trackerjacker/__main__.py", line 269
    print('Vendor for {} not found'.format(args.mac_lookup), file=sys.stderr)
                                                                 ^
SyntaxError: invalid syntax
`

**Comment by pand0rausa** [comment]
I believe this is a result of not having scapy installed.

sudo apt-get install python-scapy
