### ISSUE TITLE
Pip3 installation failed

### ISSUE THREAD

**Issue by alexelshamouty** [calebmadrigal/trackerjacker#12]
Hey guys, 

I tried installing it using pip3 it failed with the following error:

`➜  ~ pip3 install trackerjacker
Collecting trackerjacker
  Using cached https://files.pythonhosted.org/packages/d2/81/4dca960aeb78e070c1639ccbacfaa17182762f5c808c2eee0f1906c5fff4/trackerjacker-1.8.7.tar.gz
Collecting scapy==2.4.0 (from trackerjacker)
  Using cached https://files.pythonhosted.org/packages/68/01/b9943984447e7ea6f8948e90c1729b78161c2bb3eef908430638ec3f7296/scapy-2.4.0.tar.gz
Collecting pyaml>=17.12.1 (from trackerjacker)
  Using cached https://files.pythonhosted.org/packages/17/c1/5892f756109e54ed53c753129b0da4acf6b6add8dff5a85b18667553b16d/pyaml-17.12.1-py2.py3-none-any.whl
Collecting ruamel.yaml==0.15.0 (from trackerjacker)
  Using cached https://files.pythonhosted.org/packages/10/aa/f31c8a858e23fe5b14c59e6a03ae80b4cb76353c184df48a582a55eb2674/ruamel.yaml-0.15.0.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/tmp_ruamel_gzljve9b/test_ruamel_yaml.c: In function ‘main’:
    /tmp/tmp_ruamel_gzljve9b/test_ruamel_yaml.c:6:8: warning: ‘parser’ is used uninitialized in this function [-Wuninitialized]
     parser = parser;  /* prevent warning */
     ~~~~~~~^~~~~~~~
    Warning: 'keywords' should be a list, got type 'NoneType'
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i44g90yv/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/tmp/pip-install-i44g90yv/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/usr/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-i44g90yv/ruamel.yaml/
`

WIth pip2 it installed correctly but I got the following error trying to run the tool:
`╰─# python2.7 /usr/bin/trackerjacker                                                                                                                                                                                                     130 ↵
Traceback (most recent call last):
  File "/usr/bin/trackerjacker", line 11, in <module>
    load_entry_point('trackerjacker==1.8.7', 'console_scripts', 'trackerjacker')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/trackerjacker/__main__.py", line 269
    print('Vendor for {} not found'.format(args.mac_lookup), file=sys.stderr)
                                                                 ^
SyntaxError: invalid syntax
`
Any idea ?

**Comment by alexelshamouty** [comment]
Fixed this issue with using pytho3.4

`
virtualenv3 --python=/usr/bin/python3.4 trackerjacker
pip3 install trackerjacker
trackerjacker                                                                                    
`

I see that there is a pull request which changes the requirment for the ruamel version, going to test it on python 3.7

**Comment by tucked** [comment]
Dupe of #14
