### ISSUE TITLE
Map does not work on Centos7

### ISSUE THREAD

**Issue by zwieberl** [calebmadrigal/trackerjacker#15]
I installied trackerjacker from source, and after installing all the dependencies I got it to work. But unfortunately doing a `--map` gives me:

```
[root@laptop trackerjacker]# trackerjacker --map -i wlp4s0
Map output file: wifi_map.yaml
Specified map file not found - creating new map file.
Enabling monitor mode on wlp4s0
Monitoring all available channels on wlp4s0: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/trackerjacker-1.8.7-py3.4.egg/trackerjacker/__main__.py", line 229, in start
    scapy.sniff(iface=self.iface_manager.iface, prn=self.process_packet, store=0)
  File "/usr/lib/python3.4/site-packages/scapy-2.4.0-py3.4.egg/scapy/sendrecv.py", line 767, in sniff
    p = s.recv()
  File "/usr/lib/python3.4/site-packages/scapy-2.4.0-py3.4.egg/scapy/arch/linux.py", line 600, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
OSError: [Errno 100] Network is down

Sniffer error occurred. Restarting sniffer in 3 seconds...
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
command failed: Device or resource busy (-16)
... (endless loop) ...
```

**Comment by calebmadrigal** [comment]
I've seen this happen when the device fails (like if it's a USB adapter and it gets bumped). But it's also possible your adapter isn't capable of monitor mode. Does it work with other tools such as aircrack-ng?

**Comment by zwieberl** [comment]
Solved it: I had to disable NetworkManager. After that, mapping worked.

**Comment by deltaxflux** [comment]
Maybe injection test should be helpful.
`sudo aireplay-ng -9`

**Comment by zwieberl** [comment]
That is exactly what I used to find out that I had to deactivate NetworkManager in order for it to work.

**Comment by calebmadrigal** [comment]
Yep, this will happen if something else is "managing" the device.
