### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by raiden21211** [calebmadrigal/trackerjacker#29]
Hello friend, when i try to execute a command it shows me this : 
┌──(root💀kali)-[~]
└─# trackerjacker -i wlan0 --map
Traceback (most recent call last):
  File "/usr/local/bin/trackerjacker", line 5, in <module>
    from trackerjacker.__main__ import main
  File "/usr/local/lib/python3.9/dist-packages/trackerjacker/__main__.py", line 15, in <module>
    import scapy.all as scapy
  File "/usr/local/lib/python3.9/dist-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/local/lib/python3.9/dist-packages/scapy/arch/__init__.py", line 25, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/local/lib/python3.9/dist-packages/scapy/arch/bpf/core.py", line 29, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

i would like to get help, thank you.

**Comment by LightFix-Jesus** [comment]
cd /usr/lib/x86_64-linux-gnu/
sudo ln -s -f libc.a liblibc.a
