### ISSUE TITLE
module 'os' has no attribute 'getuid'

### ISSUE THREAD

**Issue by chrstphrbrj** [calebmadrigal/trackerjacker#8]
Hi, can you help me what this means?  Thank you for this.

Traceback (most recent call last):
  File "C:\Devs\python-3.6.x-x64\Scripts\trackerjacker-script.py", line 11, in <module>
    load_entry_point('trackerjacker==1.8.7', 'console_scripts', 'trackerjacker')()
  File "c:\devs\python-3.6.x-x64\lib\site-packages\trackerjacker-1.8.7-py3.6.egg\trackerjacker\__main__.py", line 284, in main
    if not os.getuid() == 0:
AttributeError: module 'os' has no attribute 'getuid'

Windows 10

**Comment by calebmadrigal** [comment]
Windows is not supported at this time.
