### ISSUE TITLE
Error installing v1.8.1 on MacOS High Sierra 10.13.6 - Python 3.7

### ISSUE THREAD

**Issue by LuisEGR** [calebmadrigal/trackerjacker#9]
I tried to install directly from pip3 `pip3 install trackerjacker` and there is an error when installing the dependency `ruamel.yaml==0.15.0`, this is the error:

```
➜  ~ pip3 install trackerjacker

Collecting trackerjacker
  Using cached https://files.pythonhosted.org/packages/d2/81/4dca960aeb78e070c1639ccbacfaa17182762f5c808c2eee0f1906c5fff4/trackerjacker-1.8.7.tar.gz
Collecting scapy==2.4.0 (from trackerjacker)
  Using cached https://files.pythonhosted.org/packages/68/01/b9943984447e7ea6f8948e90c1729b78161c2bb3eef908430638ec3f7296/scapy-2.4.0.tar.gz
Collecting pyaml>=17.12.1 (from trackerjacker)
  Using cached https://files.pythonhosted.org/packages/17/c1/5892f756109e54ed53c753129b0da4acf6b6add8dff5a85b18667553b16d/pyaml-17.12.1-py2.py3-none-any.whl
Collecting ruamel.yaml==0.15.0 (from trackerjacker)
  Using cached https://files.pythonhosted.org/packages/10/aa/f31c8a858e23fe5b14c59e6a03ae80b4cb76353c184df48a582a55eb2674/ruamel.yaml-0.15.0.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/hk/3wbrl8ys75dg5vjj2fmwf2ch0000gn/T/tmp_ruamel_azjen_h4/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/hk/3wbrl8ys75dg5vjj2fmwf2ch0000gn/T/tmp_ruamel_azjen_h4/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/hk/3wbrl8ys75dg5vjj2fmwf2ch0000gn/T/tmp_ruamel_azjen_h4/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    Warning: 'keywords' should be a list, got type 'NoneType'
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hk/3wbrl8ys75dg5vjj2fmwf2ch0000gn/T/pip-install-53csd7xw/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/private/var/folders/hk/3wbrl8ys75dg5vjj2fmwf2ch0000gn/T/pip-install-53csd7xw/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hk/3wbrl8ys75dg5vjj2fmwf2ch0000gn/T/pip-install-53csd7xw/ruamel.yaml/
```

I just saw that the previous version asked for `ruamel.yaml==0.15.0`, so I just did the instalation of that version and it's all fine:

`'pip3 install 'trackerjacker==1.8.0'`

So the current versión is broken, at least for Mac OS High Sierra - Python 3.7.0 - pip 18.0

**Comment by StevenBlack** [comment]
Same error here, can confirm that `pip3 install 'trackerjacker==1.8.0'` worked for me.

**Comment by atmanic** [comment]
Same error on macOS 10.14 Beta and the `pip3 install 'trackerjacker==1.8.0'` worked fine.

**Comment by sharipov-ru** [comment]
Kubuntu 18.05, latest pyenv, python 3.7.0 same issue and same workaround with 1.8.0 as specified version
